package org.quanphong.cinema.model;
// Generated Dec 12, 2017 1:20:26 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Movies generated by hbm2java
 */
@Entity
@Table(name = "movies", catalog = "cinema")
public class Movie implements java.io.Serializable {

	private Integer id;
	private String name;
	private String category;
	private Date dateReleased;
	private int ageAllow;
	private String mainStory;
	private int duration;

	private String language;
	private String byStudio;
	private boolean isHot;
	private String youtubeLink;
	private String imdbLink;
	
	private String posterLink;
	private String imageLink1;
	private String actors;
	private String directors;
	private int status;
	
	private Set<MovieShow> movieShowses = new HashSet<MovieShow>(0);
	

	public Movie() {
	}

	

	public Movie(Integer id, String name, String category, Date dateReleased, int ageAllow, String mainStory,
			int duration, String language, String byStudio, boolean isHot, String youtubeLink, String imdbLink,
			String posterLink, String imageLink1, String actors, String directors, int status,
			Set<MovieShow> movieShowses) {
		super();
		this.id = id;
		this.name = name;
		this.category = category;
		this.dateReleased = dateReleased;
		this.ageAllow = ageAllow;
		this.mainStory = mainStory;
		this.duration = duration;
		this.language = language;
		this.byStudio = byStudio;
		this.isHot = isHot;
		this.youtubeLink = youtubeLink;
		this.imdbLink = imdbLink;
		this.posterLink = posterLink;
		this.imageLink1 = imageLink1;
		this.actors = actors;
		this.directors = directors;
		this.status = status;
		this.movieShowses = movieShowses;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date_Released", nullable = false, length = 10)
	public Date getDateReleased() {
		return this.dateReleased;
	}

	public void setDateReleased(Date dateReleased) {
		this.dateReleased = dateReleased;
	}

	@Column(name = "ageAllow", nullable = false)
	public int getAgeAllow() {
		return this.ageAllow;
	}

	public void setAgeAllow(int ageAllow) {
		this.ageAllow = ageAllow;
	}

	@Column(name = "mainStory", nullable = false)
	public String getMainStory() {
		return this.mainStory;
	}

	public void setMainStory(String mainStory) {
		this.mainStory = mainStory;
	}

	@Column(name = "Duration", nullable = false)
	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}





	@Column(name = "Language", nullable = false, length = 10)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "byStudio", nullable = false, length = 100)
	public String getByStudio() {
		return this.byStudio;
	}

	public void setByStudio(String byStudio) {
		this.byStudio = byStudio;
	}

	@Column(name = "isHot", nullable = false)
	public boolean isIsHot() {
		return this.isHot;
	}

	public void setIsHot(boolean isHot) {
		this.isHot = isHot;
	}

	@Column(name = "youtubeLink", nullable = false)
	public String getYoutubeLink() {
		return this.youtubeLink;
	}

	public void setYoutubeLink(String youtubeLink) {
		this.youtubeLink = youtubeLink;
	}

	@Column(name = "imdbLink", nullable = false)
	public String getImdbLink() {
		return this.imdbLink;
	}

	public void setImdbLink(String imdbLink) {
		this.imdbLink = imdbLink;
	}

	

	

	@Column(name = "posterLink", nullable = false)
	public String getPosterLink() {
		return this.posterLink;
	}

	public void setPosterLink(String posterLink) {
		this.posterLink = posterLink;
	}

	@Column(name = "imageLink1")
	public String getImageLink1() {
		return this.imageLink1;
	}

	public void setImageLink1(String imageLink1) {
		this.imageLink1 = imageLink1;
	}

	

	

	@Column(name = "Status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	

	@OneToMany(mappedBy = "movies")
	public Set<MovieShow> getMovieShowses() {
		return this.movieShowses;
	}

	public void setMovieShowses(Set<MovieShow> movieShowses) {
		this.movieShowses = movieShowses;
	}


	@Column(name = "Category", nullable = false)
	public String getCategory() {
		return category;
	}


	
	public void setCategory(String category) {
		this.category = category;
	}



	@Column(name = "Actors", nullable = false)
	public String getActors() {
		return actors;
	}



	public void setActors(String actors) {
		this.actors = actors;
	}


	@Column(name = "Directors", nullable = false)
	public String getDirectors() {
		return directors;
	}



	public void setDirectors(String directors) {
		this.directors = directors;
	}



	public Movie(String name, String category, Date dateReleased, int ageAllow, String mainStory, int duration,
			String language, String byStudio, boolean isHot, String youtubeLink, String imdbLink, String posterLink,
			String imageLink1, String actors, String directors, int status) {
		super();
		this.name = name;
		this.category = category;
		this.dateReleased = dateReleased;
		this.ageAllow = ageAllow;
		this.mainStory = mainStory;
		this.duration = duration;
		this.language = language;
		this.byStudio = byStudio;
		this.isHot = isHot;
		this.youtubeLink = youtubeLink;
		this.imdbLink = imdbLink;
		this.posterLink = posterLink;
		this.imageLink1 = imageLink1;
		this.actors = actors;
		this.directors = directors;
		this.status = status;
	}



	public Movie(Integer id, String name, String category, Date dateReleased, int ageAllow, String mainStory,
			int duration, String language, String byStudio, boolean isHot, String youtubeLink, String imdbLink,
			String posterLink, String imageLink1, String actors, String directors, int status) {
		super();
		this.id = id;
		this.name = name;
		this.category = category;
		this.dateReleased = dateReleased;
		this.ageAllow = ageAllow;
		this.mainStory = mainStory;
		this.duration = duration;
		this.language = language;
		this.byStudio = byStudio;
		this.isHot = isHot;
		this.youtubeLink = youtubeLink;
		this.imdbLink = imdbLink;
		this.posterLink = posterLink;
		this.imageLink1 = imageLink1;
		this.actors = actors;
		this.directors = directors;
		this.status = status;
	}
	
	
	
	

}
