package org.quanphong.cinema.model;
// Generated Dec 12, 2017 1:20:26 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovieShows generated by hbm2java
 */
@Entity
@Table(name = "movie_shows", catalog = "cinema")
public class MovieShow implements java.io.Serializable {

	private Integer id;
	private Movie movies;
	private Room rooms;
	private Date dateShow;
	private Date beginTime;
	private Date endTime;
	private String showType;
	private int cost;
	private int status;
	private List<Ticket> ticketses;

	public MovieShow() {
	}

	public MovieShow(Movie movies, Room rooms, Date dateShow, Date beginTime, Date endTime, String showType,
			int cost, int status) {
		this.movies = movies;
		this.rooms = rooms;
		this.dateShow = dateShow;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.showType = showType;
		this.cost = cost;
		this.status = status;
	}

	public MovieShow(Movie movies, Room rooms, Date dateShow, Date beginTime, Date endTime, String showType,
			int cost, int status, List<Ticket> ticketses) {
		this.movies = movies;
		this.rooms = rooms;
		this.dateShow = dateShow;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.showType = showType;
		this.cost = cost;
		this.status = status;
		this.ticketses = ticketses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "movieID", nullable = false)
	public Movie getMovies() {
		return this.movies;
	}

	public void setMovies(Movie movies) {
		this.movies = movies;
	}

	@ManyToOne
	@JoinColumn(name = "roomID", nullable = false)
	public Room getRooms() {
		return this.rooms;
	}

	public void setRooms(Room rooms) {
		this.rooms = rooms;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateShow", nullable = false, length = 10)
	public Date getDateShow() {
		return this.dateShow;
	}

	public void setDateShow(Date dateShow) {
		this.dateShow = dateShow;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "beginTime", nullable = false, length = 8)
	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "endTime", nullable = false, length = 8)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "showType", nullable = false, length = 10)
	public String getShowType() {
		return this.showType;
	}

	public void setShowType(String showType) {
		this.showType = showType;
	}

	@Column(name = "Cost", nullable = false)
	public int getCost() {
		return this.cost;
	}

	public void setCost(int cost) {
		this.cost = cost;
	}

	@Column(name = "Status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(mappedBy = "movieShows")
	public List<Ticket> getTicketses() {
		return this.ticketses;
	}

	public void setTicketses(List<Ticket> ticketses) {
		this.ticketses = ticketses;
	}

	public MovieShow(Integer id, Movie movies, Room rooms, Date dateShow, Date beginTime, Date endTime, String showType,
			int cost, int status) {
		super();
		this.id = id;
		this.movies = movies;
		this.rooms = rooms;
		this.dateShow = dateShow;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.showType = showType;
		this.cost = cost;
		this.status = status;
	}
	
	

}
