package org.quanphong.cinema.model;
// Generated Dec 12, 2017 1:20:26 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * News generated by hbm2java
 */
@Entity
@Table(name = "news", catalog = "cinema")
public class New implements java.io.Serializable {

	private Integer id;
	private Employee employees;
	private String title;
	private String detail;
	private Date postDate;
	private Date postTime;
	private String imageLink1;
	private String imageLink2;
	private String imageLink3;
	private int status;

	public New() {
	}

	public New(Employee employees, String title, String detail, Date postDate, Date postTime, int status) {
		this.employees = employees;
		this.title = title;
		this.detail = detail;
		this.postDate = postDate;
		this.postTime = postTime;
		this.status = status;
	}

	public New(Employee employees, String title, String detail, Date postDate, Date postTime, String imageLink1,
			String imageLink2, String imageLink3, int status) {
		this.employees = employees;
		this.title = title;
		this.detail = detail;
		this.postDate = postDate;
		this.postTime = postTime;
		this.imageLink1 = imageLink1;
		this.imageLink2 = imageLink2;
		this.imageLink3 = imageLink3;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "empID", nullable = false)
	public Employee getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employee employees) {
		this.employees = employees;
	}

	@Column(name = "Title", nullable = false, length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "Detail", nullable = false, length = 65535)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "postDate", nullable = false, length = 10)
	public Date getPostDate() {
		return this.postDate;
	}

	public void setPostDate(Date postDate) {
		this.postDate = postDate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "postTime", nullable = false, length = 8)
	public Date getPostTime() {
		return this.postTime;
	}

	public void setPostTime(Date postTime) {
		this.postTime = postTime;
	}

	@Column(name = "imageLink1")
	public String getImageLink1() {
		return this.imageLink1;
	}

	public void setImageLink1(String imageLink1) {
		this.imageLink1 = imageLink1;
	}

	@Column(name = "imageLink2")
	public String getImageLink2() {
		return this.imageLink2;
	}

	public void setImageLink2(String imageLink2) {
		this.imageLink2 = imageLink2;
	}

	@Column(name = "imageLink3")
	public String getImageLink3() {
		return this.imageLink3;
	}

	public void setImageLink3(String imageLink3) {
		this.imageLink3 = imageLink3;
	}

	@Column(name = "Status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public New(Integer id, Employee employees, String title, String detail, Date postDate, Date postTime,
			String imageLink1, String imageLink2, String imageLink3, int status) {
		super();
		this.id = id;
		this.employees = employees;
		this.title = title;
		this.detail = detail;
		this.postDate = postDate;
		this.postTime = postTime;
		this.imageLink1 = imageLink1;
		this.imageLink2 = imageLink2;
		this.imageLink3 = imageLink3;
		this.status = status;
	}
	
	public boolean equals(New new1) {
		boolean ok = true;
		if (this.employees.equals(new1.getEmployees()) == false) ok = false;
		if (this.title != new1.getTitle()) ok = false;
		if (this.detail != new1.getDetail()) ok = false;
		if (this.postDate.equals(new1.getPostDate()) == false) ok = false;
		if (this.postTime.equals(new1.getPostTime()) == false) ok = false;
		if (this.imageLink1 == new1.getImageLink1()) ok = false;
		if (this.imageLink2 == new1.getImageLink2()) ok = false;
		if (this.imageLink3 == new1.getImageLink3()) ok = false;
		if (this.status == new1.getStatus()) ok = false;
		
		return ok;
	}

	public New(Integer id, Employee employees, String title, String detail, Date postDate, Date postTime, int status) {
		super();
		this.id = id;
		this.employees = employees;
		this.title = title;
		this.detail = detail;
		this.postDate = postDate;
		this.postTime = postTime;
		this.status = status;
	}
	
	
	
	
	
	

}
