package org.quanphong.cinema.model;
// Generated Dec 12, 2017 1:20:26 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "cinema", uniqueConstraints = @UniqueConstraint(columnNames = "Code"))
public class Order implements java.io.Serializable {

	private Integer id;
	private Customer customers;
	private Employee employees;
	private String code;
	private Date ordDate;
	private Date ordTime;
	private int status;
	private Set<Ticket> ticketses = new HashSet<Ticket>(0);
	private Set<OrderDetailSnack> orderDetailSnacks = new HashSet<OrderDetailSnack>(0);

	public Order() {
	}

	public Order(Customer customers, String code, Date ordDate, Date ordTime, int status) {
		this.customers = customers;
		this.code = code;
		this.ordDate = ordDate;
		this.ordTime = ordTime;
		this.status = status;
	}

	public Order(Customer customers, Employee employees, String code, Date ordDate, Date ordTime, int status,
			Set<Ticket> ticketses, Set<OrderDetailSnack> orderDetailSnacks) {
		this.customers = customers;
		this.employees = employees;
		this.code = code;
		this.ordDate = ordDate;
		this.ordTime = ordTime;
		this.status = status;
		this.ticketses = ticketses;
		this.orderDetailSnacks = orderDetailSnacks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "cusID", nullable = false)
	public Customer getCustomers() {
		return this.customers;
	}

	public void setCustomers(Customer customers) {
		this.customers = customers;
	}

	@ManyToOne
	@JoinColumn(name = "empID")
	public Employee getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employee employees) {
		this.employees = employees;
	}

	@Column(name = "Code", unique = true, nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ordDate", nullable = false, length = 10)
	public Date getOrdDate() {
		return this.ordDate;
	}

	public void setOrdDate(Date ordDate) {
		this.ordDate = ordDate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "ordTime", nullable = false, length = 8)
	public Date getOrdTime() {
		return this.ordTime;
	}

	public void setOrdTime(Date ordTime) {
		this.ordTime = ordTime;
	}

	@Column(name = "Status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(mappedBy = "orders")
	public Set<Ticket> getTicketses() {
		return this.ticketses;
	}

	public void setTicketses(Set<Ticket> ticketses) {
		this.ticketses = ticketses;
	}

	@OneToMany(mappedBy = "orders")
	public Set<OrderDetailSnack> getOrderDetailSnacks() {
		return this.orderDetailSnacks;
	}

	public void setOrderDetailSnacks(Set<OrderDetailSnack> orderDetailSnacks) {
		this.orderDetailSnacks = orderDetailSnacks;
	}

	public Order(Customer customers, Employee employees, String code, Date ordDate, Date ordTime, int status) {
		super();
		this.customers = customers;
		this.employees = employees;
		this.code = code;
		this.ordDate = ordDate;
		this.ordTime = ordTime;
		this.status = status;
	}
	
	

	public Order(Integer id, Customer customers, Employee employees, String code, Date ordDate, Date ordTime,
			int status) {
		super();
		this.id = id;
		this.customers = customers;
		this.employees = employees;
		this.code = code;
		this.ordDate = ordDate;
		this.ordTime = ordTime;
		this.status = status;
	}

	@Override
	public String toString() {
		return "Order [id=" + id + ", customers=" + customers + ", employees=" + employees + ", code=" + code
				+ ", ordDate=" + ordDate + ", ordTime=" + ordTime + ", status=" + status + ", ticketses=" + ticketses
				+ ", orderDetailSnacks=" + orderDetailSnacks + "]";
	}
	
	

}
