package org.quanphong.cinema.model;
// Generated Dec 12, 2017 1:20:26 AM by Hibernate Tools 5.1.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rooms generated by hbm2java
 */
@Entity
@Table(name = "rooms", catalog = "cinema")
public class Room implements java.io.Serializable {

	private Integer id;
	private String name;
	private int status;
	private Set<MovieShow> movieShowses = new HashSet<MovieShow>(0);
	private Set<Seat> seatses = new HashSet<Seat>(0);

	public Room() {
	}

	public Room(String name, int status) {
		this.name = name;
		this.status = status;
	}

	public Room(String name, int status, Set<MovieShow> movieShowses, Set<Seat> seatses) {
		this.name = name;
		this.status = status;
		this.movieShowses = movieShowses;
		this.seatses = seatses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 10)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(mappedBy = "rooms")
	public Set<MovieShow> getMovieShowses() {
		return this.movieShowses;
	}

	public void setMovieShowses(Set<MovieShow> movieShowses) {
		this.movieShowses = movieShowses;
	}

	@OneToMany(mappedBy = "rooms")
	public Set<Seat> getSeatses() {
		return this.seatses;
	}

	public void setSeatses(Set<Seat> seatses) {
		this.seatses = seatses;
	}

	@Override
	public String toString() {
		return "Room [id=" + id + ", name=" + name + ", status=" + status + ", movieShowses=" + movieShowses
				+ ", seatses=" + seatses + "]";
	}

	public Room(Integer id, String name, int status) {
		super();
		this.id = id;
		this.name = name;
		this.status = status;
	}
	
	

}
