package org.quanphong.cinema.model;
// Generated Dec 12, 2017 1:20:26 AM by Hibernate Tools 5.1.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Snacks generated by hbm2java
 */
@Entity
@Table(name = "snacks", catalog = "cinema")
public class Snack implements java.io.Serializable {

	private Integer id;
	private String name;
	private String imageLink;
	private int cost;
	private int status;
	private Set<OrderDetailSnack> orderDetailSnacks = new HashSet<OrderDetailSnack>(0);

	public Snack() {
	}

	public Snack(String name, String imageLink, int cost, int status) {
		this.name = name;
		this.imageLink = imageLink;
		this.cost = cost;
		this.status = status;
	}

	public Snack(String name, String imageLink, int cost, int status, Set<OrderDetailSnack> orderDetailSnacks) {
		this.name = name;
		this.imageLink = imageLink;
		this.cost = cost;
		this.status = status;
		this.orderDetailSnacks = orderDetailSnacks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ImageLink", nullable = false)
	public String getImageLink() {
		return this.imageLink;
	}

	public void setImageLink(String imageLink) {
		this.imageLink = imageLink;
	}

	@Column(name = "Cost", nullable = false)
	public int getCost() {
		return this.cost;
	}

	public void setCost(int cost) {
		this.cost = cost;
	}

	@Column(name = "Status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "snacks")
	public Set<OrderDetailSnack> getOrderDetailSnacks() {
		return this.orderDetailSnacks;
	}

	public void setOrderDetailSnacks(Set<OrderDetailSnack> orderDetailSnacks) {
		this.orderDetailSnacks = orderDetailSnacks;
	}

	public Snack(Integer id, String name, String imageLink, int cost, int status) {
		super();
		this.id = id;
		this.name = name;
		this.imageLink = imageLink;
		this.cost = cost;
		this.status = status;
	}

	
	
	

}
